### ISSUE TITLE
Generate views

### ISSUE THREAD

**Issue by nicolasiensen** [Bodacious/blogit#16]
Nice work you have been doing here!

I wa wondering if there is any way to generate the blog views? If not I'm interested in create this feature, what do you think?

**Comment by Bodacious** [comment]
@nicolaslensen - I've been wanting to add that feature for a while but haven't had a chance to do so. If you have the time to do it, that would be awesome!

**Comment by Bodacious** [comment]
@nicolasiensen This should be available with v8.0.0

**Comment by antarr** [comment]
Was this ever completed?

**Comment by marco8757** [comment]
Hi @Bodacious, is this feature ever completed? because there's no views being generated in my directory, how do i generate the views because i wish to change the styling of the view.
thanks
![screen shot 2015-09-14 at 21 49 35](https://cloud.githubusercontent.com/assets/9066883/9851297/85d6d1ec-5b2a-11e5-9844-57a0dce4e4af.png)
