### ISSUE TITLE
How to change the layout

### ISSUE THREAD

**Issue by valachi** [Bodacious/blogit#34]
Hi, could you please provide an example of how to change the default layout?

Tried this - doesn't work, all variables are nil

``` ruby
# in config/initializers/blogit.rb

module Blogit
   class PostsController < ::Blogit::ApplicationController
     layout 'blog'
   end
end
```

**Comment by Bodacious** [comment]
Yea - that won't work...

If you want to create a new layout, just for the blog, then the fastest option to achieve what you want is to create a new layout in your app `app/views/blogit/posts.html.erb`

This will be loaded automatically by Rails because it has the same name as the controller.

Other than that, there's no blogit-way to do that yet. Let me hack something up tonight

**Comment by Bodacious** [comment]
Try this:

``` ruby
# In Gemfile

gem 'blogit', github: "katanacode/blogit", branch: "master"

# In config/initializers/blogit.rb
config.layout = "my_custom_layout"
```

**Comment by valachi** [comment]
@Bodacious , Awesome! Thank you, seems to work all right!

**Comment by Bodacious** [comment]
You're welcome :smile:

**Comment by bwdolphin** [comment]
Just for reference, I had to do proper casing to get it to install correctly, aka: "KatanaCode/blogit" vs. "katanacode/blogit"
