### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by nickwales** [Bodacious/blogit#4]
The installation fails for me with:

``` ruby
rails g blogit:install
/Library/Ruby/Gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require': /Library/Ruby/Gems/1.8/gems/blogit-0.4.8/lib/blogit/configuration.rb:79: odd number list for Hash (SyntaxError)
      hard_wrap: true, 
                ^
/Library/Ruby/Gems/1.8/gems/blogit-0.4.8/lib/blogit/configuration.rb:79: syntax error, unexpected ':', expecting '}'
      hard_wrap: true, 
...
```

I have tried different versions of redcarpet which is what appears to be where it is failing from the code but to no avail. 

Any ideas?

**Comment by philou** [comment]
It looks like we are using the ruby 1.9 hash form (symbol: value) that is not parsed by your ruby 1.8.

**Comment by Bodacious** [comment]
@philou is right - we've gone for the Ruby 1.9 hash syntax - to be honest I didn't think anyone was still using Ruby 1.8 with Rails 3.

1.9.3 is the _recommended_ version to use with Rails 3 but it's not essential - not sure whether to go through the gem and modify all of the hashes to enforce backwards compatibility or make Ruby 1.9.3 a requirement for Blogit...

Thoughts?

**Comment by Bodacious** [comment]
OK so, I got as far as replacing all (I believe) of the instances of Ruby 1.9 hashes with hash rockets instead.

Trying to run the specs in Ruby 1.8.7 gave me the following error though: `factory_girl requires Ruby version >= 1.9.2.`

Since FactoryGirl is so ingrained in all of the specs, we can't afford to remove it.

I guess we have to agree that Ruby 1.9 is a requirement for Blogit.

To anyone who'd like to use this with 1.8, you could try pulling from branch **dev/Ruby1.8** and see if it works.

``` ruby
gem 'blogit', git: 'git@github.com:KatanaCode/blogit.git', branch: 'dev/Ruby1.8'
```
